CREATE DATABASE emplo;
USE emplo;
 CREATE TABLE emtb(
 E_ID VARCHAR(20) NOT NULL,
 E_NAME VARCHAR(20) NOT NULL,
 AGE INT(3) NOT NULL,
 SALARY INT(20) NOT NULL);
 
 INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("101","ANU","22","9000");
 INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("102","SHANE","29","8000");
 INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("103","ROHAN","34","6000");
 INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("104","SCOTT","44","10000");
 INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("105","TIGER","35","8000");
 INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("106","ALEX","27","7000");
 INSERT INTO  emtb(E_ID, E_NAME,AGE,SALARY)VALUES("107","ABHI","29","8000");
 SELECT * FROM emtb;
 SELECT COUNT(E_NAME) FROM emtb;
 SELECT MAX(AGE) FROM emtb;
 SELECT MIN(AGE) FROM emtb;
 SELECT SUM(AGE) FROM emtb;
 SELECT AVG(AGE) FROM emtb;
 CREATE VIEW dwany AS
 SELECT AGE FROM emtb;
 SELECT * FROM dwany;
 SELECT SALARY FROM emtb GROUP BY SALARY;
 SELECT SALARY FROM emtb ORDER BY SALARY ASC;
 SELECT SALARY FROM emtb ORDER BY SALARY DESC;